import { useCallback, useEffect, useState } from 'react';
import type { LiveState, PromptRun, TownState } from '@built-by-chat/shared';
import { Route, Routes } from 'react-router-dom';
import { Layout } from './components/Layout';
import { TownMap } from './components/TownMap';
import { Turnstile } from './components/Turnstile';
import { api } from './lib/api';
import './styles/prompt.css';

const launch = new Date('2026-08-07T00:00:00Z');
const emptyTown: TownState = { width: 12, height: 8, name: 'Tiny Internet Town', version: 1, buildings: [
  { id: 'hall', name: 'Town Hall', kind: 'civic', x: 4, y: 2, width: 2, height: 2, color: '#ff7b72', status: 'built' },
  ...[[1,1,'A'],[8,1,'B'],[8,5,'C']].map(([x,y,n]) => ({ id: `lot-${n}`, name: `Empty Lot ${n}`, kind: 'empty', x: Number(x), y: Number(y), width: 2, height: 2, color: '#26345c', status: 'planned' as const }))
], residents: [{ id: 'pip', name: 'Pip', role: 'Town caretaker', x: 6, y: 4, color: '#5de4c7' }], events: [] };

function Countdown() {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const seconds = Math.max(0, Math.floor((launch.getTime() - now) / 1000));
  const parts = [['days', Math.floor(seconds / 86400)], ['hours', Math.floor(seconds % 86400 / 3600)], ['minutes', Math.floor(seconds % 3600 / 60)], ['seconds', seconds % 60]] as const;
  return <div className="countdown" aria-label={`Premiere begins in ${parts.map(([k,v]) => `${v} ${k}`).join(', ')}`}>{parts.map(([label, value]) => <div key={label}><strong>{String(value).padStart(2,'0')}</strong><span>{label}</span></div>)}</div>;
}

function Home() {
  return <>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">A LIVE-BUILT DIGITAL TOWN</p><h1>You vote.<br /><em>We build.</em><br />The town grows.</h1><p className="lede">Tiny Internet Town is a living illustrated world shaped live by the people watching. Every building, resident, and ridiculous town problem starts with your vote.</p><div className="actions"><a className="button primary" href="/live">Enter the live room <span>→</span></a><a className="button secondary" href="/town">Explore the town</a></div><p className="micro">Free to participate · No account required</p></div><div className="hero-art"><img src="/brand/hero-town.png" alt="A cozy midnight digital town glowing beside a winding cyan river" /><div className="status-card"><span className="signal" /> <div><small>NEXT LIVE BUILD</small><strong>Founding Day</strong><span>Thursday · 7:00 PM CT</span></div></div></div></section>
    <section className="premiere"><div><p className="eyebrow coral">PUBLIC PREMIERE</p><h2>Thursday, August 6</h2><p>7:00 PM Central · YouTube + Twitch</p></div><Countdown /><a className="button pale" href="/built-by-chat.ics">Add to calendar</a></section>
    <section className="how"><p className="eyebrow">HOW IT WORKS</p><h2>Watch a world get made by everyone.</h2><div className="steps"><article><b>01</b><h3>We open a question</h3><p>What belongs on Main Street? Who moves in? What weird crisis hits next?</p></article><article><b>02</b><h3>The internet votes</h3><p>Free, protected voting on this site. Change your mind until the poll closes.</p></article><article><b>03</b><h3>Phaenex builds it live</h3><p>Code, art, lore, and happy accidents—broadcast to YouTube and Twitch.</p></article><article><b>04</b><h3>The town remembers</h3><p>Every decision becomes part of the map, credits, and permanent town history.</p></article></div></section>
    <section className="schedule"><div><p className="eyebrow coral">THE WEEKLY RHYTHM</p><h2>Build Thursday.<br />Town Hall Sunday.</h2></div><article><span>THU</span><div><strong>Live Build</strong><p>7:00–9:00 PM CT</p></div></article><article><span>SUN</span><div><strong>Playtest + Town Hall</strong><p>3:00 PM CT</p></div></article></section>
  </>;
}

function Live() {
  const [state, setState] = useState<LiveState | null>(null); const [error, setError] = useState(''); const [token, setToken] = useState(''); const [selected, setSelected] = useState(''); const [receipt, setReceipt] = useState('');
  useEffect(() => { void api.session().then(api.state).then(setState).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Live room unavailable')); }, []);
  useEffect(() => {
    if (!state?.show || state.show.status !== 'live') return;
    const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:'; const socket = new WebSocket(`${protocol}//${location.host}/api/live/${state.show.id}/socket`);
    socket.onmessage = (event) => { try { const message = JSON.parse(String(event.data)) as { state?: LiveState; counts?: Record<string,number> }; if (message.state) setState((old) => ({ ...message.state!, show: old?.show ?? null })); else if (message.counts) setState((old) => old ? ({ ...old, counts: message.counts! }) : old); } catch { /* ignore malformed event */ } };
    return () => socket.close();
  }, [state?.show?.id]);
  const vote = async () => { if (!state?.poll || !selected || !token) return; try { const result = await api.vote(state.poll.id, selected, token, crypto.randomUUID()); setReceipt(`Vote saved${result.changed ? ' — your previous choice was replaced' : ''}.`); } catch (e) { setReceipt(e instanceof Error ? e.message : 'Vote failed'); } };
  return <section className="page live-page"><p className="eyebrow coral">LIVE ROOM</p><h1>{state?.show?.title ?? 'The town is getting ready.'}</h1><p className="lede">{state?.show?.objective ?? 'The next objective and audience vote will appear here when the show begins.'}</p>{error && <div className="notice error" role="alert">{error}</div>}
    {state?.poll?.status === 'open' ? <div className="poll-card"><div className="poll-meta"><span className="signal" /> VOTING OPEN <span>{state.connectedViewers} connected</span></div><h2>{state.poll.question}</h2><div className="poll-options">{state.poll.options.map((option) => { const count = state.counts[option.id] ?? 0; return <label key={option.id} className={selected === option.id ? 'selected' : ''}><input type="radio" name="vote" value={option.id} checked={selected === option.id} onChange={() => setSelected(option.id)} /><span><strong>{option.label}</strong><small>{option.description}</small></span><b>{count}</b></label>; })}</div><Turnstile onToken={setToken} /><button className="button primary" disabled={!selected || !token} onClick={() => void vote()}>Save my vote</button><p className="micro" aria-live="polite">{receipt || 'You can change your choice until voting closes.'}</p></div> : <div className="empty-state"><span>☾</span><h2>No vote is open yet</h2><p>Come back Thursday at 7:00 PM CT. Live counts and the current build objective will appear here.</p></div>}
  </section>;
}

function Town() { const [town, setTown] = useState(emptyTown); useEffect(() => { void api.town().then(setTown).catch(() => undefined); }, []); return <section className="page town-page"><p className="eyebrow">CURRENT MAP · VERSION {town.version}</p><h1>{town.name}</h1><p className="lede">A 12 × 8 patch of possibility. Use the map labels with a screen reader or explore visually.</p><TownMap town={town} /><div className="legend"><span><i className="built" /> Built</span><span><i className="open" /> Open lot</span><span><i className="river" /> River</span></div><section className="latest"><p className="eyebrow coral">LATEST TOWN UPDATE</p><h2>The lights are on.</h2><p>Town Hall is standing, Pip is keeping watch, and three lots are waiting for their future. On Founding Day, the internet chooses what happens next.</p></section></section>; }

const episodes = ['Founding Day','Main Street','Meet the Neighbors','The Town’s First Crisis','The Internet Town Council','The First Festival'];
function Roadmap() { return <section className="page"><p className="eyebrow coral">SEASON ONE</p><h1>Six nights to make a town.</h1><p className="lede">The destination is open. The audience chooses the roads we take.</p><div className="roadmap">{episodes.map((title,i) => <article key={title}><b>{String(i+1).padStart(2,'0')}</b><div><span>{i === 0 ? 'NEXT' : 'PLANNED'}</span><h2>{title}</h2><p>{['Name the town, choose its first landmark, and meet its first resident.','Create a business, its owner, its look, and what it gives the town.','Add homes, personalities, relationships, and community needs.','Choose an absurd problem and build the town’s response.','Set laws, resources, priorities, and a visible civic dashboard.','Throw a festival, revisit the history, and choose what comes next.'][i]}</p></div></article>)}</div></section>; }
function Credits() { return <section className="page"><p className="eyebrow">COMMUNITY LEDGER</p><h1>Every good town remembers its builders.</h1><div className="empty-state"><span>✦</span><h2>The first credits are waiting.</h2><p>Approved ideas, episode decisions, contributors, testers, and moderators will appear here after Founding Day.</p></div></section>; }

function Support() {
  const [form,setForm] = useState({ title:'', body:'', creditName:'', consent:false }); const [token,setToken]=useState(''); const [message,setMessage]=useState(''); const onToken=useCallback((value:string)=>setToken(value),[]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api.session(); await api.idea({ ...form, turnstileToken: token }); setMessage('Idea received. It will be reviewed before appearing publicly.'); } catch(e) { setMessage(e instanceof Error ? e.message : 'Submission failed'); } };
  return <section className="page"><p className="eyebrow coral">SUPPORT THE TOWN</p><h1>Participation stays free.</h1><p className="lede">Watching, voting, and submitting ideas cost nothing. Optional support links will only appear after the brand accounts are approved.</p><div className="support-grid"><article><h2>Share an idea</h2><form onSubmit={(e)=>void submit(e)}><label>Idea title<input value={form.title} maxLength={120} required onChange={e=>setForm({...form,title:e.target.value})} /></label><label>What should happen?<textarea value={form.body} maxLength={2000} required onChange={e=>setForm({...form,body:e.target.value})} /></label><label>Name to credit (optional)<input value={form.creditName} maxLength={80} onChange={e=>setForm({...form,creditName:e.target.value})} /></label><label className="check"><input type="checkbox" checked={form.consent} required onChange={e=>setForm({...form,consent:e.target.checked})} /><span>I grant Built by Chat permission to adapt, publish, commercialize, and credit this contribution under the submission terms.</span></label><Turnstile onToken={onToken} /><button className="button primary" disabled={!token || !form.consent}>Send for moderation</button><p aria-live="polite">{message}</p></form></article><aside><h2>Commercial inquiries</h2><p>Sponsors can support the show without buying votes, decisions, ownership, or moderation influence.</p><a className="button secondary" href="mailto:sponsors@builtbychat.com">sponsors@builtbychat.com</a><h3>Supporter promise</h3><p>Any future paid perks will stay behind the scenes. Core votes remain open to everyone.</p></aside></div></section>;
}

function Studio() {
  const [runs, setRuns] = useState<PromptRun[]>([]); const [historyError, setHistoryError] = useState('');
  useEffect(() => { void api.promptRuns().then(setRuns).catch((error: unknown) => setHistoryError(error instanceof Error ? error.message : 'Prompt history unavailable')); }, []);
  return <section className="page studio"><p className="eyebrow coral">PRIVATE CONTROL ROOM</p><h1>Studio</h1><div className="notice">This route is protected at the edge with Cloudflare Access. Production API calls also require the authenticated Access email header.</div><div className="studio-grid"><article><span>SHOW</span><h2>Founding Day</h2><button className="button primary">Start show</button></article><article><span>ACTIVE POLL</span><h2>No poll open</h2><button className="button secondary">Prepare poll</button></article><article><span>OVERLAY</span><h2>Welcome</h2><button className="button secondary">Send to OBS</button></article><article className="studio-ledger"><span>PROMPT LEDGER · PRIVATE</span><h2>Audience intent → verified build</h2><p className="lede">Every AI-assisted run records its decision source, template version, bounded context, checks, cost, and human disposition. Raw chat, secrets, private moderation material, and hidden reasoning are excluded.</p>{historyError ? <p className="notice error" role="alert">{historyError}</p> : runs.length ? <div className="prompt-history">{runs.slice(0, 10).map((run) => <div key={run.id}><strong>{run.purpose}</strong><span>{run.templateSlug}@{run.templateVersion} · {run.disposition}</span><small>{run.decisionSummary ?? run.inputSummary}</small></div>)}</div> : <p className="micro">No prompt runs recorded yet. History appears here after the first scoped run.</p>}</article></div></section>;
}
function Legal({kind}:{kind:'privacy'|'terms'}) { return <section className="page legal"><p className="eyebrow">{kind==='privacy'?'PRIVACY':'SUBMISSION TERMS'}</p><h1>{kind==='privacy'?'Privacy, without the fog.':'Ideas can join the town.'}</h1>{kind==='privacy'?<><p>Built by Chat uses an opaque signed browser identifier to keep one current choice per poll. Network identifiers are hashed with a rotating secret; raw IP addresses are not stored in application data. Public vote totals never reveal voter identities.</p><p>Ideas retain the credit name you choose and are held for moderation. Operational audit records are restricted to studio administrators. See <a href="/PRIVACY.md">the repository policy</a> for retention and contact details.</p></>:<><p>By checking the consent box, you give Built by Chat a non-exclusive, worldwide, perpetual permission to adapt, publish, display, perform, distribute, and commercialize your submitted idea, with credit where reasonably practical.</p><p>You confirm the idea is yours to share. Submission does not guarantee use, payment, ownership, or a particular creative decision. You keep ownership of your original contribution.</p></>}</section>; }

export function App() { return <Routes><Route element={<Layout />}><Route index element={<Home />} /><Route path="live" element={<Live />} /><Route path="town" element={<Town />} /><Route path="roadmap" element={<Roadmap />} /><Route path="credits" element={<Credits />} /><Route path="support" element={<Support />} /><Route path="studio" element={<Studio />} /><Route path="privacy" element={<Legal kind="privacy" />} /><Route path="terms" element={<Legal kind="terms" />} /></Route></Routes>; }
