const escapeHtml = (value) => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');

export function livingDraft({ title, subtitle, storageKey, sections }) {
  const fields=sections.map((section,index)=>`<label class="field"><span>${String(index+1).padStart(2,'0')} · ${escapeHtml(section.label)}</span><small>${escapeHtml(section.help ?? '')}</small>${section.multiline===false?`<input id="${escapeHtml(section.id)}" value="${escapeHtml(section.value)}">`:`<textarea id="${escapeHtml(section.id)}" rows="${section.rows ?? 5}">${escapeHtml(section.value)}</textarea>`}<button type="button" data-copy="${escapeHtml(section.id)}">Copy</button></label>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title>
<style>:root{color-scheme:dark;--bg:#090e20;--panel:#111936;--line:#2d3b67;--ink:#eef6ff;--muted:#a8b7d6;--lime:#b9f53d;--coral:#ff6b5f;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink)}header,main{max-width:1180px;margin:auto;padding:2rem}header{display:grid;grid-template-columns:1fr auto;gap:2rem;align-items:end;border-bottom:1px solid var(--line)}.eyebrow,.field>span,.gate>span{font:700 .65rem ui-monospace;letter-spacing:.12em;color:var(--coral)}h1{font-size:clamp(2.5rem,6vw,5.5rem);margin:.6rem 0;line-height:.95}p,small{color:var(--muted);line-height:1.55}.status{border-top:3px solid var(--coral);padding-top:1rem}.status strong{display:block;font-size:1.5rem}.toolbar{display:flex;gap:.6rem;flex-wrap:wrap;margin:2rem 0}.toolbar button,.field button{background:transparent;color:var(--ink);border:1px solid var(--line);padding:.65rem .9rem;cursor:pointer}.toolbar button.primary{background:var(--lime);color:#111;border-color:var(--lime);font-weight:900}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.field{position:relative;display:flex;flex-direction:column;gap:.6rem;padding:1.2rem;background:var(--panel);border:1px solid var(--line)}.field small{min-height:2.2em}.field input,.field textarea{width:100%;background:#070b19;color:var(--ink);border:1px solid #40527c;padding:.9rem;font:500 .78rem/1.6 ui-monospace;resize:vertical}.field button{align-self:flex-start}.release{margin-top:3rem;padding:2rem;border:1px solid var(--line)}.release h2{font-size:2rem}.gates{display:grid;grid-template-columns:1fr 1fr}.gate{display:flex;gap:.8rem;padding:1rem;border-top:1px solid var(--line)}.gate input{accent-color:var(--lime)}#verdict{color:var(--coral);font-weight:900}.complete #verdict{color:var(--lime)}.micro{font:600 .65rem ui-monospace;color:var(--muted)}@media(max-width:700px){header,.grid{grid-template-columns:1fr}.gates{grid-template-columns:1fr}main,header{padding:1rem}}</style></head>
<body><header><div><p class="eyebrow">LIVING PRODUCTION ARTIFACT · LOCAL AUTO-SAVE</p><h1>${escapeHtml(title)}</h1><p>${escapeHtml(subtitle)}</p></div><aside class="status"><span class="eyebrow">RELEASE STATE</span><strong>DRAFT</strong><small>Explicit Phaenex approval required</small></aside></header>
<main><div class="toolbar"><button class="primary" type="button" id="copy-receipt">Copy making receipt</button><button type="button" onclick="window.print()">Print / save PDF</button><span class="micro" id="save-state" aria-live="polite">Ready</span></div><section class="grid">${fields}</section>
<section class="release" id="release"><p class="eyebrow">ANTI-SLOP RELEASE GATE</p><h2>Would this deserve attention without the AI story?</h2><p id="verdict" aria-live="polite">0/8 · Hold the artifact</p><div class="gates">${['Specific promise','Real audience consequence','Named human responsibility','Visible rejection or revision','Clear provenance and rights','Independent verification','Durable artifact or lesson','Worth the attention and workload'].map((label,index)=>`<label class="gate"><input type="checkbox" data-gate="${index}"><span>${String(index+1).padStart(2,'0')}</span><strong>${label}</strong></label>`).join('')}</div></section></main>
<script>const key=${JSON.stringify(storageKey)};const controls=[...document.querySelectorAll('input,textarea,select')];const saved=JSON.parse(localStorage.getItem(key)||'{}');for(const control of controls){const id=control.id||control.dataset.gate;if(id in saved){if(control.type==='checkbox')control.checked=Boolean(saved[id]);else control.value=String(saved[id])}}function refresh(){const state={};for(const control of controls){const id=control.id||control.dataset.gate;state[id]=control.type==='checkbox'?control.checked:control.value}localStorage.setItem(key,JSON.stringify(state));const pass=document.querySelectorAll('[data-gate]:checked').length;document.querySelector('#release').classList.toggle('complete',pass===8);document.querySelector('#verdict').textContent=pass+'/8 · '+(pass===8?'Ready for human release review':pass>=5?'Revise before release':'Hold the artifact');document.querySelector('#save-state').textContent='Saved locally · '+new Date().toLocaleTimeString()}controls.forEach(control=>control.addEventListener('input',refresh));refresh();document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const field=document.getElementById(button.dataset.copy);await navigator.clipboard.writeText(field.value);button.textContent='Copied';setTimeout(()=>button.textContent='Copy',1200)}));document.querySelector('#copy-receipt').addEventListener('click',async()=>{const ids=['decision','interpretation','ai-role','revision','verification','learning','shipped'];const value=ids.map(id=>{const field=document.getElementById(id);return field?field.previousElementSibling.previousElementSibling.textContent+'\n'+field.value:''}).filter(Boolean).join('\n\n');await navigator.clipboard.writeText(value);document.querySelector('#copy-receipt').textContent='Receipt copied';setTimeout(()=>document.querySelector('#copy-receipt').textContent='Copy making receipt',1200)});</script></body></html>`;
}
